modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="avatar"
version="${file.jarVersion}"
displayName="Avatar: Frontiers of Pandora - Dragon Edition"
authors="Igor Dragon"
description='''
Avatar: Frontiers of Pandora inspired Minecraft mod.
Explore Pandora, discover its creatures and become part of the Na'vi world.
'''

[[dependencies.avatar]]
    modId="forge"
    mandatory=true
    versionRange="[47.2.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.avatar]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"